# $Id: ts_aws.rb,v 1.17 2009/06/03 23:25:33 ianmacd Exp $
#

require 'test/unit'
require 'tc_amazon'
require 'tc_aws'
require 'tc_browse_node_lookup'
require 'tc_customer_content_lookup'
require 'tc_help'
require 'tc_item_lookup'
require 'tc_item_search'
require 'tc_list_lookup'
require 'tc_list_search'
require 'tc_multiple_operation'
require 'tc_operation_request'
require 'tc_seller_listing_lookup'
require 'tc_seller_listing_search'
require 'tc_seller_lookup'
require 'tc_serialisation'
require 'tc_similarity_lookup'
require 'tc_shopping_cart'
require 'tc_tag_lookup'
require 'tc_transaction_lookup'
require 'tc_vehicle_operations'
