#!/usr/bin/ruby -w
#
# $Id: help1,v 1.2 2010/02/20 16:49:12 ianmacd Exp $

require 'amazon/aws/search'

include Amazon::AWS
include Amazon::AWS::Search

h = Help.new( 'ResponseGroup', 'Large' )
h.response_group = ResponseGroup.new( 'Help' )

req = Request.new
req.locale = 'uk'

resp = req.search( h )
help = resp.help_response[0].information.response_group_information

printf( "The response group 'Large' was created on %s\n", help.creation_date )
puts 'It can be used with the following operations:'
puts help.valid_operations.operation.join( ', ' )
puts
puts "and causes the following elements to be returned:\n\n"
puts help.elements.element
